#pragma once

#include <windows.h>

struct {
  FARPROC ptr[256];

  void DllInit(HMODULE hModule) {
    for (int i = 0; i < 256; i++) {
      ptr[i] = GetProcAddress(hModule, MAKEINTRESOURCEA(i));
    }
  }
} dll;

void _Ordinal_2() { dll.ptr[2](); }
void _mciExecute() { dll.ptr[3](); }
void _CloseDriver() { dll.ptr[4](); }
void _DefDriverProc() { dll.ptr[5](); }
void _DriverCallback() { dll.ptr[6](); }
void _DrvGetModuleHandle() { dll.ptr[7](); }
void _GetDriverModuleHandle() { dll.ptr[8](); }
void _OpenDriver() { dll.ptr[9](); }
void _PlaySound() { dll.ptr[10](); }
void _PlaySoundA() { dll.ptr[11](); }
void _PlaySoundW() { dll.ptr[12](); }
void _SendDriverMessage() { dll.ptr[13](); }
void _WOWAppExit() { dll.ptr[14](); }
void _auxGetDevCapsA() { dll.ptr[15](); }
void _auxGetDevCapsW() { dll.ptr[16](); }
void _auxGetNumDevs() { dll.ptr[17](); }
void _auxGetVolume() { dll.ptr[18](); }
void _auxOutMessage() { dll.ptr[19](); }
void _auxSetVolume() { dll.ptr[20](); }
void _joyConfigChanged() { dll.ptr[21](); }
void _joyGetDevCapsA() { dll.ptr[22](); }
void _joyGetDevCapsW() { dll.ptr[23](); }
void _joyGetNumDevs() { dll.ptr[24](); }
void _joyGetPos() { dll.ptr[25](); }
void _joyGetPosEx() { dll.ptr[26](); }
void _joyGetThreshold() { dll.ptr[27](); }
void _joyReleaseCapture() { dll.ptr[28](); }
void _joySetCapture() { dll.ptr[29](); }
void _joySetThreshold() { dll.ptr[30](); }
void _mciDriverNotify() { dll.ptr[31](); }
void _mciDriverYield() { dll.ptr[32](); }
void _mciFreeCommandResource() { dll.ptr[33](); }
void _mciGetCreatorTask() { dll.ptr[34](); }
void _mciGetDeviceIDA() { dll.ptr[35](); }
void _mciGetDeviceIDFromElementIDA() { dll.ptr[36](); }
void _mciGetDeviceIDFromElementIDW() { dll.ptr[37](); }
void _mciGetDeviceIDW() { dll.ptr[38](); }
void _mciGetDriverData() { dll.ptr[39](); }
void _mciGetErrorStringA() { dll.ptr[40](); }
void _mciGetErrorStringW() { dll.ptr[41](); }
void _mciGetYieldProc() { dll.ptr[42](); }
void _mciLoadCommandResource() { dll.ptr[43](); }
void _mciSendCommandA() { dll.ptr[44](); }
void _mciSendCommandW() { dll.ptr[45](); }
void _mciSendStringA() { dll.ptr[46](); }
void _mciSendStringW() { dll.ptr[47](); }
void _mciSetDriverData() { dll.ptr[48](); }
void _mciSetYieldProc() { dll.ptr[49](); }
void _midiConnect() { dll.ptr[50](); }
void _midiDisconnect() { dll.ptr[51](); }
void _midiInAddBuffer() { dll.ptr[52](); }
void _midiInClose() { dll.ptr[53](); }
void _midiInGetDevCapsA() { dll.ptr[54](); }
void _midiInGetDevCapsW() { dll.ptr[55](); }
void _midiInGetErrorTextA() { dll.ptr[56](); }
void _midiInGetErrorTextW() { dll.ptr[57](); }
void _midiInGetID() { dll.ptr[58](); }
void _midiInGetNumDevs() { dll.ptr[59](); }
void _midiInMessage() { dll.ptr[60](); }
void _midiInOpen() { dll.ptr[61](); }
void _midiInPrepareHeader() { dll.ptr[62](); }
void _midiInReset() { dll.ptr[63](); }
void _midiInStart() { dll.ptr[64](); }
void _midiInStop() { dll.ptr[65](); }
void _midiInUnprepareHeader() { dll.ptr[66](); }
void _midiOutCacheDrumPatches() { dll.ptr[67](); }
void _midiOutCachePatches() { dll.ptr[68](); }
void _midiOutClose() { dll.ptr[69](); }
void _midiOutGetDevCapsA() { dll.ptr[70](); }
void _midiOutGetDevCapsW() { dll.ptr[71](); }
void _midiOutGetErrorTextA() { dll.ptr[72](); }
void _midiOutGetErrorTextW() { dll.ptr[73](); }
void _midiOutGetID() { dll.ptr[74](); }
void _midiOutGetNumDevs() { dll.ptr[75](); }
void _midiOutGetVolume() { dll.ptr[76](); }
void _midiOutLongMsg() { dll.ptr[77](); }
void _midiOutMessage() { dll.ptr[78](); }
void _midiOutOpen() { dll.ptr[79](); }
void _midiOutPrepareHeader() { dll.ptr[80](); }
void _midiOutReset() { dll.ptr[81](); }
void _midiOutSetVolume() { dll.ptr[82](); }
void _midiOutShortMsg() { dll.ptr[83](); }
void _midiOutUnprepareHeader() { dll.ptr[84](); }
void _midiStreamClose() { dll.ptr[85](); }
void _midiStreamOpen() { dll.ptr[86](); }
void _midiStreamOut() { dll.ptr[87](); }
void _midiStreamPause() { dll.ptr[88](); }
void _midiStreamPosition() { dll.ptr[89](); }
void _midiStreamProperty() { dll.ptr[90](); }
void _midiStreamRestart() { dll.ptr[91](); }
void _midiStreamStop() { dll.ptr[92](); }
void _mixerClose() { dll.ptr[93](); }
void _mixerGetControlDetailsA() { dll.ptr[94](); }
void _mixerGetControlDetailsW() { dll.ptr[95](); }
void _mixerGetDevCapsA() { dll.ptr[96](); }
void _mixerGetDevCapsW() { dll.ptr[97](); }
void _mixerGetID() { dll.ptr[98](); }
void _mixerGetLineControlsA() { dll.ptr[99](); }
void _mixerGetLineControlsW() { dll.ptr[100](); }
void _mixerGetLineInfoA() { dll.ptr[101](); }
void _mixerGetLineInfoW() { dll.ptr[102](); }
void _mixerGetNumDevs() { dll.ptr[103](); }
void _mixerMessage() { dll.ptr[104](); }
void _mixerOpen() { dll.ptr[105](); }
void _mixerSetControlDetails() { dll.ptr[106](); }
void _mmDrvInstall() { dll.ptr[107](); }
void _mmGetCurrentTask() { dll.ptr[108](); }
void _mmTaskBlock() { dll.ptr[109](); }
void _mmTaskCreate() { dll.ptr[110](); }
void _mmTaskSignal() { dll.ptr[111](); }
void _mmTaskYield() { dll.ptr[112](); }
void _mmioAdvance() { dll.ptr[113](); }
void _mmioAscend() { dll.ptr[114](); }
void _mmioClose() { dll.ptr[115](); }
void _mmioCreateChunk() { dll.ptr[116](); }
void _mmioDescend() { dll.ptr[117](); }
void _mmioFlush() { dll.ptr[118](); }
void _mmioGetInfo() { dll.ptr[119](); }
void _mmioInstallIOProcA() { dll.ptr[120](); }
void _mmioInstallIOProcW() { dll.ptr[121](); }
void _mmioOpenA() { dll.ptr[122](); }
void _mmioOpenW() { dll.ptr[123](); }
void _mmioRead() { dll.ptr[124](); }
void _mmioRenameA() { dll.ptr[125](); }
void _mmioRenameW() { dll.ptr[126](); }
void _mmioSeek() { dll.ptr[127](); }
void _mmioSendMessage() { dll.ptr[128](); }
void _mmioSetBuffer() { dll.ptr[129](); }
void _mmioSetInfo() { dll.ptr[130](); }
void _mmioStringToFOURCCA() { dll.ptr[131](); }
void _mmioStringToFOURCCW() { dll.ptr[132](); }
void _mmioWrite() { dll.ptr[133](); }
void _mmsystemGetVersion() { dll.ptr[134](); }
void _sndPlaySoundA() { dll.ptr[135](); }
void _sndPlaySoundW() { dll.ptr[136](); }
void _timeBeginPeriod() { dll.ptr[137](); }
void _timeEndPeriod() { dll.ptr[138](); }
void _timeGetDevCaps() { dll.ptr[139](); }
void _timeGetSystemTime() { dll.ptr[140](); }
void _timeGetTime() { dll.ptr[141](); }
void _timeKillEvent() { dll.ptr[142](); }
void _timeSetEvent() { dll.ptr[143](); }
void _waveInAddBuffer() { dll.ptr[144](); }
void _waveInClose() { dll.ptr[145](); }
void _waveInGetDevCapsA() { dll.ptr[146](); }
void _waveInGetDevCapsW() { dll.ptr[147](); }
void _waveInGetErrorTextA() { dll.ptr[148](); }
void _waveInGetErrorTextW() { dll.ptr[149](); }
void _waveInGetID() { dll.ptr[150](); }
void _waveInGetNumDevs() { dll.ptr[151](); }
void _waveInGetPosition() { dll.ptr[152](); }
void _waveInMessage() { dll.ptr[153](); }
void _waveInOpen() { dll.ptr[154](); }
void _waveInPrepareHeader() { dll.ptr[155](); }
void _waveInReset() { dll.ptr[156](); }
void _waveInStart() { dll.ptr[157](); }
void _waveInStop() { dll.ptr[158](); }
void _waveInUnprepareHeader() { dll.ptr[159](); }
void _waveOutBreakLoop() { dll.ptr[160](); }
void _waveOutClose() { dll.ptr[161](); }
void _waveOutGetDevCapsA() { dll.ptr[162](); }
void _waveOutGetDevCapsW() { dll.ptr[163](); }
void _waveOutGetErrorTextA() { dll.ptr[164](); }
void _waveOutGetErrorTextW() { dll.ptr[165](); }
void _waveOutGetID() { dll.ptr[166](); }
void _waveOutGetNumDevs() { dll.ptr[167](); }
void _waveOutGetPitch() { dll.ptr[168](); }
void _waveOutGetPlaybackRate() { dll.ptr[169](); }
void _waveOutGetPosition() { dll.ptr[170](); }
void _waveOutGetVolume() { dll.ptr[171](); }
void _waveOutMessage() { dll.ptr[172](); }
void _waveOutOpen() { dll.ptr[173](); }
void _waveOutPause() { dll.ptr[174](); }
void _waveOutPrepareHeader() { dll.ptr[175](); }
void _waveOutReset() { dll.ptr[176](); }
void _waveOutRestart() { dll.ptr[177](); }
void _waveOutSetPitch() { dll.ptr[178](); }
void _waveOutSetPlaybackRate() { dll.ptr[179](); }
void _waveOutSetVolume() { dll.ptr[180](); }
void _waveOutUnprepareHeader() { dll.ptr[181](); }
void _waveOutWrite() { dll.ptr[182](); }